/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    { type: 'autogenerated', dirName: 'intro' },
  ],
  conceptsSidebar: [
    { type: 'autogenerated', dirName: 'concepts' },
  ],
  tutorialsSidebar: [
    { type: 'autogenerated', dirName: 'tutorials' },
  ],
  providersSidebar: [
    { type: 'autogenerated', dirName: 'providers' },
  ],
  cliSidebar: [
    { type: 'autogenerated', dirName: 'cli' },
  ],
};

module.exports = sidebars;
