name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Checkout DefangLabs/defang
        uses: actions/checkout@v3
        with:
          repository: DefangLabs/defang
          path: defang
          ref: main

      - name: Checkout DefangLabs/samples
        uses: actions/checkout@v3
        with:
          repository: DefangLabs/samples
          path: samples
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Pre-build
        run: npm run prebuild

      - name: Test build website
        run: npm run build
